<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="mauricio-hp-laptop" failures="2" tests="8" name="Surefire test" time="0.128" errors="0" timestamp="2020-12-23T13:30:53 PET">
  <testcase classname="examen.TestFunctionClass" name="CreateInstanceTest" time="0.05"/>
  <testcase classname="examen.TestFunctionClass" name="CreatePieceTest" time="0.002">
    <failure type="java.lang.AssertionError" message="Lists differ at element [0]: examen.Point@3679d92e != examen.Point@47b11ec7 expected [examen.Point@3679d92e] but found [examen.Point@47b11ec7]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [0]: examen.Point@3679d92e != examen.Point@47b11ec7 expected [examen.Point@3679d92e] but found [examen.Point@47b11ec7]
at examen.TestFunctionClass.CreatePieceTest(TestFunctionClass.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- CreatePieceTest -->
  <testcase classname="examen.TestFunctionClass" name="checkCompletionsTest" time="0.001"/>
  <testcase classname="examen.TestFunctionClass" name="checkSetPiece" time="0.003"/>
  <testcase classname="examen.TestFunctionClass" name="checkStatusTest" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at examen.TestFunctionClass.checkStatusTest(TestFunctionClass.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusTest -->
  <testcase classname="examen.TestFunctionClass" name="createPlayerTest" time="0.0"/>
  <testcase classname="examen.TestFunctionClass" name="generatePointTest" time="0.0"/>
  <testcase classname="examen.TestFunctionClass" name="generateRandomPieceTest" time="0.001"/>
</testsuite> <!-- Surefire test -->
